# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-07 11:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FeeStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sem', models.IntegerField()),
                ('sem_fee_status', models.BooleanField()),
                ('hostel_fee_status', models.CharField(max_length=50)),
                ('bus_fee_status', models.CharField(max_length=50)),
                ('mess_fee_status', models.CharField(max_length=50)),
                ('late_fee_status', models.CharField(max_length=50)),
                ('deposit_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='FeeStructure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=50)),
                ('sem_fee', models.IntegerField()),
                ('hostel_fee', models.IntegerField()),
                ('bus_fee', models.IntegerField()),
                ('mess_fee', models.IntegerField()),
                ('late_fee', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='StudentFeeInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OnlineFeeSystem.FeeStructure')),
            ],
        ),
        migrations.CreateModel(
            name='StudentInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enroll_id', models.CharField(max_length=30, unique=True)),
                ('enroll_time', models.DateTimeField()),
                ('student_name', models.CharField(max_length=100)),
                ('fathers_name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('branch', models.CharField(max_length=50)),
                ('mobile_no', models.IntegerField(max_length=15)),
                ('fees_status', models.BooleanField()),
                ('student_type', models.CharField(max_length=50)),
                ('sem', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='studentfeeinfo',
            name='student_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OnlineFeeSystem.StudentInfo'),
        ),
        migrations.AddField(
            model_name='feestatus',
            name='student_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OnlineFeeSystem.StudentInfo'),
        ),
    ]
