# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-07 11:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OnlineFeeSystem', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feestatus',
            old_name='student_id',
            new_name='student',
        ),
        migrations.RenameField(
            model_name='studentfeeinfo',
            old_name='fee_id',
            new_name='fee',
        ),
        migrations.RenameField(
            model_name='studentfeeinfo',
            old_name='student_id',
            new_name='student',
        ),
        migrations.AlterField(
            model_name='studentinfo',
            name='mobile_no',
            field=models.IntegerField(),
        ),
    ]
