# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-10 10:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OnlineFeeSystem', '0004_auto_20171109_0936'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentinfo',
            name='email_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
