# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-10 11:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OnlineFeeSystem', '0005_studentinfo_email_confirmed'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentinfo',
            name='token',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
