# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-03 11:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeacherStudentFeedback', '0002_remove_student_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='password',
            field=models.CharField(default=None, max_length=40),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='teacher',
            name='password',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='student_rating',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='student_remarks',
            field=models.CharField(max_length=50),
        ),
    ]
