# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-03 11:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeacherStudentFeedback', '0003_auto_20171103_1150'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='student_rating',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='student_remarks',
        ),
        migrations.AddField(
            model_name='student',
            name='student_rating',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='student_remarks',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
    ]
