# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-07 11:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeacherStudentFeedback', '0005_auto_20171103_1246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_rating',
            field=models.IntegerField(null=True),
        ),
    ]
